#!/usr/bin/env python3
"""repo_signals.py — objective hotspot detection for a code quality review.

Collects cheap, deterministic signals so a reviewer knows where to spend expensive
reading attention. Standard library only, no network, read-only.

    python3 repo_signals.py <path> [--format md|json] [options]

EVERY line of output is a HYPOTHESIS, not a finding. Heuristics produce false
positives: a "duplicate block" may be legitimately similar, a "swallowed exception"
may be deliberate and documented, a "long function" may be a fine state machine.
Open the cited lines and read them before reporting anything.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from collections import defaultdict

# --------------------------------------------------------------------------- config

SKIP_DIRS = {
    ".git", ".hg", ".svn", "node_modules", "vendor", "venv", ".venv", "env",
    "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".tox",
    "dist", "build", "target", "out", "bin", "obj", ".next", ".nuxt",
    "coverage", "htmlcov", ".idea", ".vscode", ".gradle", "Pods",
    "site-packages", ".terraform", "migrations_backup",
}

CODE_EXT = {
    ".py": "python", ".pyi": "python",
    ".js": "js", ".jsx": "js", ".mjs": "js", ".cjs": "js",
    ".ts": "ts", ".tsx": "ts",
    ".java": "java", ".kt": "kotlin", ".kts": "kotlin", ".scala": "scala",
    ".go": "go", ".rs": "rust", ".rb": "ruby", ".php": "php",
    ".cs": "csharp", ".c": "c", ".h": "c", ".cc": "cpp", ".cpp": "cpp",
    ".hpp": "cpp", ".m": "objc", ".swift": "swift",
    ".sh": "shell", ".bash": "shell", ".zsh": "shell",
    ".sql": "sql", ".tf": "terraform", ".vue": "vue", ".svelte": "svelte",
}

GENERATED_HINTS = (
    "@generated", "auto-generated", "autogenerated", "do not edit",
    "code generated by", "this file was generated",
)

# (label, regex, note) — grouped so the report explains what to check.
RISK_PATTERNS = [
    # error handling
    ("swallowed-exception", r"except\s*[\w\.\, ()]*:\s*(pass|\.\.\.)\s*$", "exception discarded"),
    ("swallowed-exception", r"catch\s*\([^)]*\)\s*\{\s*\}", "empty catch block"),
    ("swallowed-exception", r"\.catch\(\s*\(\s*\)\s*=>\s*\{\s*\}\s*\)", "empty promise catch"),
    ("swallowed-exception", r"except\s+Exception\b", "over-broad except"),
    ("swallowed-exception", r"catch\s*\(\s*(Throwable|Exception)\s+\w+\s*\)", "over-broad catch"),
    ("ignored-error", r"^\s*_\s*[,=]\s*[\w\.]+\(", "Go: error assigned to _"),
    ("bare-except", r"except\s*:", "bare except catches everything"),
    # band-aid markers
    ("bandaid-marker", r"\b(TODO|FIXME|XXX|HACK|KLUDGE|WORKAROUND|TEMPORARY|TEMP FIX|QUICK FIX)\b", "unfinished or patched"),
    ("bandaid-sleep", r"\b(time\.sleep|Thread\.sleep|sleep|setTimeout)\s*\(\s*\d", "timing-based synchronization"),
    ("bandaid-retry", r"\b(retry|retries|max_attempts|MAX_RETRIES)\b", "retry logic — check idempotency and cause"),
    # debug leftovers
    ("debug-leftover", r"\b(console\.log|console\.debug|debugger|pdb\.set_trace|breakpoint\(\)|binding\.pry|var_dump|dd\()", "debug statement"),
    ("debug-leftover", r"^\s*print\s*\(", "print() in library code"),
    # security
    ("security-exec", r"\b(eval|exec|Function\(|new Function|system\(|popen|shell_exec)\s*\(", "dynamic execution"),
    ("security-shell", r"shell\s*=\s*True", "subprocess with shell=True"),
    ("security-tls", r"(verify\s*=\s*False|rejectUnauthorized\s*:\s*false|InsecureSkipVerify\s*:\s*true|CURLOPT_SSL_VERIFYPEER\s*,\s*0)", "TLS verification disabled"),
    ("security-xss", r"(innerHTML\s*=|dangerouslySetInnerHTML|v-html)", "unescaped HTML sink"),
    ("security-deser", r"(pickle\.loads|yaml\.load\s*\((?!.*Loader)|unserialize\()", "unsafe deserialization"),
    ("security-secret", r"(?i)(api[_-]?key|secret|password|passwd|token|private[_-]?key)\s*[:=]\s*[\"'][^\"']{8,}[\"']", "possible hardcoded secret"),
    ("security-weak-hash", r"\b(md5|sha1)\s*\(", "weak hash — check if used for security"),
    ("security-random", r"\brandom\.(random|randint|choice)\b", "non-CSPRNG — check if used for tokens"),
    # reliability
    ("no-timeout", r"\b(requests\.(get|post|put|delete|patch)|urlopen|fetch|axios\.(get|post)|http\.Get)\s*\(", "check for a timeout argument"),
    ("select-star", r"SELECT\s+\*", "SELECT * couples code to schema"),
    ("dangerous-sql", r"\b(DELETE\s+FROM|UPDATE)\b(?!.*\bWHERE\b)", "DML without WHERE"),
    # structure
    ("deep-nesting-marker", r"^\s{20,}\S", "20+ spaces of indentation"),
    ("commented-out-code", r"^\s*(#|//)\s*(if|for|while|def|function|class|return|import|const|let|var)\b", "commented-out code"),
    ("magic-flag", r"\b(if|elif)\s+.*==\s*[\"'][a-z_]+[\"']\s*:?\s*(#|//|$)", "string comparison — candidate for enum"),
]

SQL_KEYWORD = re.compile(r"\b(SELECT|INSERT\s+INTO|UPDATE|DELETE\s+FROM|WHERE|ORDER\s+BY)\b", re.I)
SQL_INTERP = re.compile(r"(\"\s*\+|\+\s*\"|'\s*\+|\+\s*'|f\"|f'|\.format\(|%\s*\(|%s\"|\$\{|#\{)")
EXCEPT_HEAD = re.compile(r"^\s*(except\b.*:|catch\s*\(.*\)\s*\{?)\s*$")
EMPTY_BODY = re.compile(r"^\s*(pass|\.\.\.|\}|return\s*(None|nil|null)?;?)\s*$")


def combined_checks(lines):
    """Checks that a single-line regex cannot express reliably."""
    hits = []
    for i, line in enumerate(lines):
        if SQL_KEYWORD.search(line) and SQL_INTERP.search(line):
            hits.append(("security-sql-building", i + 1,
                         "SQL assembled from a string — confirm the input source", line))
        if EXCEPT_HEAD.match(line):
            nxt = lines[i + 1] if i + 1 < len(lines) else ""
            if EMPTY_BODY.match(nxt):
                hits.append(("swallowed-exception", i + 1,
                             "handler body discards the error", line))
    return hits


FUNC_START = {
    "python": re.compile(r"^(\s*)(async\s+)?def\s+(\w+)"),
    "js": re.compile(r"^(\s*)(export\s+)?(async\s+)?(function\s+(\w+)|const\s+(\w+)\s*=\s*(async\s*)?\()"),
    "ts": re.compile(r"^(\s*)(export\s+)?(async\s+)?(function\s+(\w+)|const\s+(\w+)\s*=\s*(async\s*)?\()"),
    "go": re.compile(r"^(\s*)func\s+(\([^)]*\)\s*)?(\w+)"),
    "java": re.compile(r"^(\s+)(public|private|protected|static|final|\s)*[\w<>\[\],\s]+\s+(\w+)\s*\([^;]*\)\s*\{"),
    "kotlin": re.compile(r"^(\s*)(private\s+|public\s+|internal\s+)?(suspend\s+)?fun\s+(\w+)"),
    "ruby": re.compile(r"^(\s*)def\s+(\w+)"),
    "php": re.compile(r"^(\s*)(public|private|protected|static|\s)*function\s+(\w+)"),
    "csharp": re.compile(r"^(\s+)(public|private|protected|internal|static|async|\s)+[\w<>\[\],\s]+\s+(\w+)\s*\([^;]*\)\s*\{"),
    "rust": re.compile(r"^(\s*)(pub\s+)?(async\s+)?fn\s+(\w+)"),
}

DEFAULTS = dict(big_file=400, huge_file=800, long_func=60, dup_window=6, top=25)

# --------------------------------------------------------------------------- helpers


def norm_line(line: str) -> str:
    """Normalize a line for duplicate detection: collapse whitespace, drop string
    and numeric literals so cosmetic differences do not hide a real copy-paste."""
    s = line.strip()
    s = re.sub(r"\"[^\"]*\"|'[^']*'", '""', s)
    s = re.sub(r"\b\d+(\.\d+)?\b", "0", s)
    s = re.sub(r"\s+", " ", s)
    return s


def is_trivial(s: str) -> bool:
    return len(s) < 12 or s in {"{", "}", "});", "return", "break", "continue", "else:", "} else {"}


def indent_of(line: str) -> int:
    return len(line) - len(line.lstrip(" \t"))


COMMENT_START = ("#", "//", "/*", "*", "--", "<!--", '"""', "'''", ";")


def is_generated(text: str) -> bool:
    """True only when a generated-file marker appears in a comment near the top."""
    for line in text.splitlines()[:15]:
        s = line.strip()
        if not s or not s.startswith(COMMENT_START):
            continue
        low = s.lower()
        if any(h in low for h in GENERATED_HINTS):
            return True
    return False


def walk(root: str, max_bytes: int, skipped: list):
    """Yield (relpath, lang, text). Every file that is NOT yielded is recorded in
    `skipped` with a reason — a scan that silently drops files gives a false sense of
    coverage, which is the exact failure this tool exists to prevent."""
    for dirpath, dirnames, filenames in os.walk(root):
        pruned = [d for d in dirnames if d in SKIP_DIRS or d.startswith(".")]
        for d in pruned:
            skipped.append({"file": os.path.relpath(os.path.join(dirpath, d), root) + "/",
                            "reason": "directory excluded by default"})
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS and not d.startswith(".")]
        for fn in filenames:
            path = os.path.join(dirpath, fn)
            rel = os.path.relpath(path, root)
            ext = os.path.splitext(fn)[1].lower()
            if ext not in CODE_EXT:
                continue  # not source code; not part of the reviewable set
            try:
                if os.path.getsize(path) > max_bytes:
                    skipped.append({"file": rel, "reason": f"larger than --max-bytes ({max_bytes})"})
                    continue
                with open(path, "r", encoding="utf-8", errors="replace") as fh:
                    text = fh.read()
            except OSError as exc:
                skipped.append({"file": rel, "reason": f"unreadable: {exc.__class__.__name__}"})
                continue
            # Only a *comment* in the first few lines counts as a generated-file marker.
            # Scanning the raw head instead matches any file that merely mentions the
            # phrase — including this one — and drops real source from the scan.
            if is_generated(text):
                skipped.append({"file": rel, "reason": "looks generated (header comment)"})
                continue
            yield rel, CODE_EXT[ext], text


# --------------------------------------------------------------------------- analysis


def analyze(root: str, cfg: dict) -> dict:
    files, risks, long_funcs = [], defaultdict(list), []
    windows = defaultdict(list)
    totals = defaultdict(int)
    skipped: list = []
    broken_patterns: set = set()

    for relpath, lang, text in walk(root, cfg["max_bytes"], skipped):
        lines = text.splitlines()
        n = len(lines)
        blank = sum(1 for ln in lines if not ln.strip())
        totals["files"] += 1
        totals["lines"] += n
        totals[f"lang:{lang}"] += 1

        max_indent = 0
        for i, line in enumerate(lines, 1):
            if line.strip():
                max_indent = max(max_indent, indent_of(line))
            for label, pattern, note in RISK_PATTERNS:
                try:
                    if re.search(pattern, line):
                        risks[label].append(
                            {"file": relpath, "line": i, "note": note, "text": line.strip()[:160]}
                        )
                except re.error as exc:  # a broken pattern must not fail silently
                    if label not in broken_patterns:
                        broken_patterns.add(label)
                        print(f"warning: pattern '{label}' is invalid and was skipped: {exc}",
                              file=sys.stderr)

        for label, lineno, note, text in combined_checks(lines):
            risks[label].append(
                {"file": relpath, "line": lineno, "note": note, "text": text.strip()[:160]}
            )

        files.append(
            {"file": relpath, "lang": lang, "lines": n, "blank": blank, "max_indent": max_indent}
        )

        # long functions (indent/brace heuristic)
        rx = FUNC_START.get(lang)
        if rx:
            starts = []
            for i, line in enumerate(lines):
                m = rx.match(line)
                if m:
                    name = next((g for g in m.groups()[1:] if g and g.isidentifier()), "?")
                    starts.append((i, indent_of(line), name))
            for idx, (i, ind, name) in enumerate(starts):
                end = starts[idx + 1][0] if idx + 1 < len(starts) else len(lines)
                body = [ln for ln in lines[i:end] if ln.strip()]
                if len(body) >= cfg["long_func"]:
                    long_funcs.append(
                        {"file": relpath, "line": i + 1, "name": name, "length": len(body)}
                    )

        # duplicate windows
        w = cfg["dup_window"]
        norm = [norm_line(ln) for ln in lines]
        for i in range(0, max(0, n - w + 1)):
            chunk = [s for s in norm[i:i + w] if s and not s.startswith(("#", "//", "*"))]
            if len(chunk) < w or sum(1 for s in chunk if is_trivial(s)) > w // 2:
                continue
            key = hashlib.sha1("\n".join(chunk).encode()).hexdigest()[:16]
            windows[key].append((relpath, i + 1))

    # merge hits that land on the same label+file+line so one line is reported once
    for label, hits in risks.items():
        merged = {}
        for h in hits:
            k = (h["file"], h["line"])
            if k in merged:
                if h["note"] not in merged[k]["note"]:
                    merged[k]["note"] += "; " + h["note"]
            else:
                merged[k] = dict(h)
        risks[label] = sorted(merged.values(), key=lambda h: (h["file"], h["line"]))

    dups = []
    for key, locs in windows.items():
        distinct_files = {f for f, _ in locs}
        if len(locs) < 2:
            continue
        # keep cross-file matches, or same-file matches that are far apart
        if len(distinct_files) == 1 and max(l for _, l in locs) - min(l for _, l in locs) < 40:
            continue
        dups.append({"hash": key, "count": len(locs),
                     "locations": [{"file": f, "line": l} for f, l in sorted(locs)[:8]]})
    dups.sort(key=lambda d: (-d["count"], d["locations"][0]["file"]))

    files.sort(key=lambda f: -f["lines"])
    long_funcs.sort(key=lambda f: -f["length"])
    return {
        "root": os.path.abspath(root),
        "totals": dict(totals),
        "files": files,
        "long_functions": long_funcs,
        "duplicate_blocks": dups,
        "risks": {k: v for k, v in sorted(risks.items())},
        "skipped": sorted(skipped, key=lambda s: s["file"]),
        "broken_patterns": sorted(broken_patterns),
        "config": {k: v for k, v in cfg.items()},
    }


# --------------------------------------------------------------------------- output


def render_md(r: dict, cfg: dict) -> str:
    t, top = r["totals"], cfg["top"]
    langs = ", ".join(f"{k[5:]}={v}" for k, v in sorted(t.items()) if k.startswith("lang:"))
    out = [
        "# Repo signals",
        "",
        f"Root: `{r['root']}`",
        f"Files scanned: {t.get('files', 0)} · total lines: {t.get('lines', 0)} · {langs}",
        "",
        "> Every item below is a HYPOTHESIS produced by a regex or a heuristic. Open the cited",
        "> lines and read them before reporting anything as a finding.",
        "",
        f"## Largest files (review candidates, >{cfg['big_file']} lines)",
        "",
    ]
    big = [f for f in r["files"] if f["lines"] > cfg["big_file"]][:top]
    if big:
        out += ["| File | Lines | Max indent | Lang |", "|---|---|---|---|"]
        out += [f"| `{f['file']}` | {f['lines']} | {f['max_indent']} | {f['lang']} |" for f in big]
    else:
        out.append("_None._")

    out += ["", f"## Long functions (>= {cfg['long_func']} non-blank lines)", ""]
    lf = r["long_functions"][:top]
    if lf:
        out += ["| Function | Location | Lines |", "|---|---|---|"]
        out += [f"| `{f['name']}` | `{f['file']}:{f['line']}` | {f['length']} |" for f in lf]
    else:
        out.append("_None._")

    out += ["", f"## Duplicate blocks (>= {cfg['dup_window']} normalized lines, repeated)", ""]
    if r["duplicate_blocks"]:
        out.append("Literals and numbers are normalized, so near-copies match. **The differences")
        out.append("between copies are where bugs hide — diff them, do not just count them.**")
        out.append("")
        for d in r["duplicate_blocks"][:top]:
            locs = ", ".join(f"`{l['file']}:{l['line']}`" for l in d["locations"])
            out.append(f"- {d['count']}× — {locs}")
    else:
        out.append("_None detected at this window size._")

    out += ["", "## Pattern hits", ""]
    if r["risks"]:
        for label, hits in r["risks"].items():
            out.append(f"### {label} — {len(hits)} hit(s)")
            for h in hits[:top]:
                out.append(f"- `{h['file']}:{h['line']}` — {h['note']} — `{h['text']}`")
            if len(hits) > top:
                out.append(f"- _…{len(hits) - top} more_")
            out.append("")
    else:
        out.append("_None._")

    out += ["## Not scanned", ""]
    if r["skipped"]:
        out.append("Coverage is only meaningful if you know what was left out. Decide explicitly")
        out.append("whether each of these needs a manual look; do not let them disappear.")
        out.append("")
        for s in r["skipped"][:top]:
            out.append(f"- `{s['file']}` — {s['reason']}")
        if len(r["skipped"]) > top:
            out.append(f"- _…{len(r['skipped']) - top} more_")
    else:
        out.append("_Nothing skipped._")
    out.append("")

    out += [
        "## Suggested next steps",
        "",
        "1. Deep-read the largest / most-nested files that sit on a critical path.",
        "2. Diff each duplicate group and record how the copies diverge.",
        "3. For every `swallowed-exception` and `bandaid-*` hit, find the cause it hides.",
        "4. Confirm each `security-*` hit against the real data flow before reporting it.",
        "5. Discard every hypothesis the code disproves — do not pad the report.",
        "",
    ]
    return "\n".join(out)


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("path", nargs="?", default=".", help="repo or directory to scan")
    p.add_argument("--format", choices=["md", "json"], default="md")
    p.add_argument("--big-file", type=int, default=DEFAULTS["big_file"])
    p.add_argument("--long-func", type=int, default=DEFAULTS["long_func"])
    p.add_argument("--dup-window", type=int, default=DEFAULTS["dup_window"])
    p.add_argument("--top", type=int, default=DEFAULTS["top"], help="max rows per section")
    p.add_argument("--max-bytes", type=int, default=1_500_000, help="skip files larger than this")
    a = p.parse_args(argv)

    if not os.path.isdir(a.path):
        print(f"error: not a directory: {a.path}", file=sys.stderr)
        return 2

    cfg = dict(big_file=a.big_file, long_func=a.long_func, dup_window=a.dup_window,
               top=a.top, max_bytes=a.max_bytes)
    result = analyze(a.path, cfg)
    text = json.dumps(result, indent=2) if a.format == "json" else render_md(result, cfg)
    try:
        print(text)
    except BrokenPipeError:  # piped into head/less
        os.dup2(os.open(os.devnull, os.O_WRONLY), sys.stdout.fileno())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
